### ISSUE TITLE
Federation does not work with Private and Direct Jinxes

### ISSUE THREAD

**Issue by Aldarone** [WitchesTown/mastodon#1]
Witches should be able to send Private and Direct Jinxes to other instances but it currently doesn't work.

**Comment by Ragzouken** [comment]
Just a comment to add the datapoints:
I've received a remote private message from someone i don't follow
I've had a remote private conversation with mutual follower

point being, if dms arent working sometimes i dont think its about who the individual is following

**Comment by Aldarone** [comment]
Private jinxes now federate, thanks to v1.3.0
