### ISSUE TITLE
I need more GIFs

### ISSUE THREAD

**Issue by Aldarone** [WitchesTown/mastodon#10]
So here it is, I don't find GIFs fast enough for the witching hours so I need your help.

Anytime you find a GIF of a door / gate / portal / whatever opening or closing or anything witchy come here, post in in the comments of this issue or jinx it with [#witchhourgif](https://witches.town/tags/witchhourgif).

I'm deleting the gifs here when I add them to the gatekeeper bot. Thank you @Sigafoos, @rbebel, @MxDoomicorn, @Seipas for your help.

**Comment by Maverynthia** [comment]
Can it be a fly in through a gate? I think I might be able to make some :3

**Comment by Sigafoos** [comment]
![rainbow window](https://gifwrapped.co/dropbox/2f0ioawoxktdlqk/giphy%203.gif)

**Comment by Sigafoos** [comment]
Aw dang

![rainbow window](https://dl.dropboxusercontent.com/s/2f0ioawoxktdlqk/giphy%203.gif)

**Comment by Sigafoos** [comment]
![door open](https://dl.dropboxusercontent.com/s/xeavmdfxput4n8q/0RN2siY.gif)

**Comment by Sigafoos** [comment]
![hocus pocus](https://media.giphy.com/media/Ffn4bXyvZUa6Q/giphy.gif)

**Comment by rbebel** [comment]
![locked-down-firefox](https://cloud.githubusercontent.com/assets/4470779/25071958/e9fc0626-22c3-11e7-8c6a-9d0d8b041efb.gif)

**Comment by rbebel** [comment]
![open](https://cloud.githubusercontent.com/assets/4470779/25071960/ff0d8508-22c3-11e7-8720-2f67fcf890d0.gif)

**Comment by rbebel** [comment]
![open-cat](https://cloud.githubusercontent.com/assets/4470779/25071966/22adf86c-22c4-11e7-99a5-a15159b351f7.gif)
![open-catndogs](https://cloud.githubusercontent.com/assets/4470779/25071970/2c1cf60a-22c4-11e7-907a-8035269ff6cf.gif)
![open-jumanji](https://cloud.githubusercontent.com/assets/4470779/25071971/303a52b4-22c4-11e7-8a22-d36dc7978d5f.gif)
![open-2](https://cloud.githubusercontent.com/assets/4470779/25071979/4e837f2a-22c4-11e7-86ac-99d737487f0d.gif)

**Comment by MxDoomicorn** [comment]
![giphy 4](https://cloud.githubusercontent.com/assets/27664510/25079668/a7de16d2-233e-11e7-8dd5-d4345bc39ec9.gif)

![giphy 7](https://cloud.githubusercontent.com/assets/27664510/25079696/d42bc40a-233e-11e7-9d8c-c9d32a8e65bd.gif)

**Comment by Maverynthia** [comment]
![tongaridoor](https://cloud.githubusercontent.com/assets/2293000/25111938/04ac0770-23bc-11e7-9389-7763c8d53774.gif)

Got the door gif finished :3 It's from Tongari Boushi, which is an NDS/3DS game about going to witch school.

**Comment by MxDoomicorn** [comment]
I found two more!

![giphy 12](https://cloud.githubusercontent.com/assets/27664510/25257338/a18cd4d4-2637-11e7-92e2-a872caeeeb7a.gif)

![giphy 10](https://cloud.githubusercontent.com/assets/27664510/25257353/c1875d18-2637-11e7-9eaa-d4db3c9be49d.gif)

**Comment by Seipas** [comment]
![De monstre et company](https://media.giphy.com/media/2w5vEj38z6JNK/giphy.gif) [version alternative](https://38.media.tumblr.com/dd035bc37ea58df313b74e9a3770d1a4/tumblr_mouzbwxoK51qhcrb0o1_500.gif)

**Comment by Seipas** [comment]
[Je sais pas trop si ça fit mais j'ai essayé d'en trouver une de Little Witch Academia](https://fat.gfycat.com/CourageousAgreeableAsianporcupine.mp4)

**Comment by Seipas** [comment]
![De l'étrange noël de Monsieur Jack](https://38.media.tumblr.com/tumblr_m9ukawyZzt1r85lwto1_500.gif)

**Comment by Sylvhem** [comment]
I have some GIF to suggest.

# Doors' opening

- [Diagon Alley doors](https://25.media.tumblr.com/tumblr_lybb4z67BE1qf0kb5o1_500.gif)
- [Hagrid cracking a door open](https://68.media.tumblr.com/f4c6f744cc8262c05b69c6b61f530715/tumblr_inline_nrsgslzl4j1ty58pl_500.gif) (maybe to flashy, could this cause seizure?)
- [TARDIS' doors opening](http://i58.photobucket.com/albums/g246/sey115/tumblr_m4llnl2lcP1qjxl1no1_500_zps0694d4aa.gif)
