### ISSUE TITLE
Étoile rouge inversée

### ISSUE THREAD

**Issue by Seyjin** [WitchesTown/mastodon#13]
Salut salut,

Voilà ma petite astuce pour l'icone Sigil : 

  button.icon-button[title~=sigil], .fa-star {
    transform: rotate(180deg);
  }
  button.icon-button.active[title~="sigil"], .notification__message .fa-star {
    filter: saturate(100) hue-rotate(359deg) brightness(83%);
  }

**Comment by Aldarone** [comment]
Merci ! T'as du remarquer que je l'ai intégré un peu différemment (aussi j'étais pas fan du rouge)
