### ISSUE TITLE
pentacle icon is misaligned in individual jinx view

### ISSUE THREAD

**Issue by Sigafoos** [WitchesTown/mastodon#16]
The pentacle is awesome! But there's a bit of css needed to align it when viewing a jinx in the rightmost column.

![5fca34](https://cloud.githubusercontent.com/assets/417845/25535098/f675f6d4-2c03-11e7-8b7a-bc767c53b10f.png)

This only happens for the selected jinx, not for others in a conversation ([example](https://witches.town/@dconley/1053543))

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Sigafoos** [comment]
I think the issue is that the pentacle icon is bigger than the boost. Shrinking `.detailed-status__link
 .fa-star`'s `font-size` to 11px (and adding `font-weight: bold`) produces this, which I think looks better:

![ft11](https://cloud.githubusercontent.com/assets/417845/25535588/a018bdba-2c05-11e7-85ad-4d98140f302e.png)

And while I was there I tried making all `.fa-star` be bold. I like the look: what do others think?

![e2df7e](https://cloud.githubusercontent.com/assets/417845/25535620/c861fd2c-2c05-11e7-9912-f5d9044e8fe4.png)

**Comment by Aldarone** [comment]
Yeah that's way better !

Thank you !
