### ISSUE TITLE
English Libera Pay link on /about/more is broken

### ISSUE THREAD

**Issue by benhamill** [WitchesTown/mastodon#21]
The link to the Libera Pay support page at the bottom of `/about/more` (at the very bottom, at the end of the English section) goes to https://liberapay.com/Witches, but that page is missing. I'm fairly sure it should go to https://liberapay.com/WitchesTown, which is where the same link in the French section goes.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Aldarone** [comment]
Thanks for your report !
