### ISSUE TITLE
Notifications don't clear

### ISSUE THREAD

**Issue by Kevin-Garber** [WitchesTown/mastodon#4]
In the notifications column, if you click the "clear notifications" button, the column doesn't clear.  Confirmed this with other users. 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Kevin-Garber** [comment]
Saw this was listed in main repo, apologies.

**Comment by Aldarone** [comment]
I don't mind having this type of issue open even if the problem is know upstream. It provides a quick glance for witches instead of having to search in the hundreds of open issues upstream.

And I can close them from the merge commit when I'm doing upgrades.

Can you include the reference here ?

**Comment by Kevin-Garber** [comment]
Here we go.

https://github.com/tootsuite/mastodon/issues/1259
