### ISSUE TITLE
Loading bar color is not "awesome witch purple"

### ISSUE THREAD

**Issue by wryk** [WitchesTown/mastodon#8]
It's only a simple css rule but the element doesn't have an id or a class

element css selector : `.ui > div:nth-child(4) > div:nth-child(1)`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Aldarone** [comment]
Fixed in 50b2250085d5f2430cb9a798a3ec77e3abd5e482
