### ISSUE TITLE
Jinxes from people witches don't follow appears in the cauldron

### ISSUE THREAD

**Issue by Aldarone** [WitchesTown/mastodon#9]
It's a known Mastodon issue : tootsuite/mastodon#1601

**Comment by Sylvhem** [comment]
It looks like [it have been closed upstream](https://github.com/tootsuite/mastodon/issues/1601#issuecomment-309495256). Apparently, it's [an odd but normal behavior](https://github.com/tootsuite/mastodon/issues/2817#issuecomment-299501175). Maybe we should consider closing this?
